### PR TITLE
Support dotnet build (on Windows)

### LINKED ISSUE #48: SlowCheetah Task not compatible with .NET CLI
In an attempt to update my EF Core first database ... I run `dotnet ef database update`.

This results in the following error:

> C:\Users\Alon\.nuget\packages\microsoft.visualstudio.slowcheetah\3.0.61\build\Microsoft.VisualStudio.SlowCheetah.targets(83,5): error MSB4062: The "TransformTask" task could not be loaded from the assembly C:\Users\Alon\.nuget\packages\microsoft.visualstudio.slowcheetah\3.0.61\build\..\tools\Microsoft.VisualStudio.SlowCheetah.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

Others are experiencing this same exact issue ... from [SO](https://stackoverflow.com/questions/44140052/dotnet-build-fails-but-building-works-in-visual-studio-slowcheetah).

Any chance this project is being bit by the same thing that the SO [mentions](https://github.com/dotnet/cli/issues/5457)?

"DotNet" commands worked no problem before installing SlowCheetah. Any suggestions? (Which would also help the OP in the SO issue as well!)

### PR DESCRIPTION
**Pull request by jviau**
Fixes `dotnet build` commands on windows. Cross-plat support has not been tested yet, that is tracked by #83.

Closes #48

### CODE REVIEW

**Comment by trygvelo** [comment]
@jviau When will this be pushed to NuGet?

**Comment by martinoss** [comment]
Any update on NuGet availability?

**Comment by DanLomanto** [comment]
@jviau any idea when we might get a new build with this fix?  This issue is preventing my team from moving forward with some new work that we're anxiously trying to complete.  Thanks!

**Comment by maxisam** [comment]
@jviau  Could you do pre-release? at least we can test it?

**Pull request merged**
