### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by cemsagan**
fixed typos in cs files below:

`TransformFailedException.cs`
`ITransformer.cs`
`PackageUtilitiesTest.cs`

### CODE REVIEW

**Review by lifengl — APPROVED** [review]

**Review by adrianvmsft — APPROVED** [review]

**Comment by adrianvmsft** [comment]
@cemsagan - I think this change is ready to go in, are you able to complete the merge? If not, I can complete it.
Thank you!
Adrian

**Comment by cemsagan** [comment]
> @cemsagan - I think this change is ready to go in, are you able to complete the merge? If not, I can complete it. Thank you! Adrian

@adrianvmsft It looks like I'm unable to complete the merge. Could you please complete it for me? Thanks!

**Comment by soroshsabz** [comment]
Any update?

**Review by adrianvmsft — APPROVED** [review]

**Comment by adrianvmsft** [comment]
> Any update?

Hi,
I am really sorry about the delay, it completely slipped my mind.
Thanks,
Adrian

**Comment by adrianvmsft** [comment]
I am still trying to get the build pipeline to work, so you may see multiple attempts to run it :)
Please ignore them, the pipeline issues are not related to your change, but this is a good opportunity to get it working :)

**Pull request merged**
